### ISSUE TITLE
TS errors or breaking changes in 2.0.7

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [zenorocha/clipboard.js#735]
## 🐛 Bug Report

After upgrading from 2.0.6 to 2.0.7 I started getting TS errors, see the codesandbox reproduction:

https://codesandbox.io/s/kind-water-by1vw?file=/src/index.ts
(code based on README.md)

For 2.0.6 I was using `@types/clipboard`, looks like ts definitions were added in 2.0.7, however it seems that they don't match the provided examples and if the examples need update then it would be breaking change which would require new major version (3.0)

### Have you read the [Contributing Guidelines on issues](https://github.com/zenorocha/clipboard.js/blob/master/contributing.md)?

Sure I did

### Expected Behaviour

no ts errors

### Actual Behaviour

ts errors

```
Type '() => string' is not assignable to type 'string'.ts(2322)
```
```
Type '() => string' is not assignable to type '"cut" | "copy" | undefined'.
  Type '() => string' is not assignable to type '"copy"'.ts(2322)
```
```
Property 'on' does not exist on type 'ClipboardJS'.ts(2339)
```

### To Reproduce

https://codesandbox.io/s/kind-water-by1vw?file=/src/index.ts

### Browsers Affected

n/a

### Operational System

n/a

**Comment by vitormalencar** [comment]
@jacekkarczmarczyk Thanks for the bug report, I will be having a look into soon

**Comment by gitdust** [comment]
same issue when use webpack for build
back to 2.0.6 is fine

**Comment by vitormalencar** [comment]
@gitdust I believe that this is more related to the webpackBuild not to the type definitions 
you can have a look at issue #737

**Comment by lucmarques-uol** [comment]
Hi @vitormalencar , I'm here to let you know that my team at BoaCompra has also been affected by this issue, we had to momentarily downgrade to 2.0.6 as well. I'll keep watching this issue for updates.

**Comment by vitormalencar** [comment]
@lucmarques-uol thanks for reaching out, the PR is already made, it will be available probably in the next release.

**Comment by vitormalencar** [comment]
So I just took some time today to create a new release, I included the Typescript Types changes I hope it helps to solve the issue, if not I will continue to push more fixes =)

Please let me know if the issue is solved or not

**Comment by jacekkarczmarczyk** [comment]
Looks good for me, thanks!
