### ISSUE TITLE
error on clipboardjs.com

### ISSUE THREAD

**Issue by ChrRaz** [zenorocha/clipboard.js#177]
Hi,
It seems that the [demo site](https://clipboardjs.com/) recently broke.
Upon page load the `demos.js` file and the `snippets.js` files throw an error claiming that "Clipboard is not a constructor".
Because of the error the rest of the script is not executed rendering the site nonfunctional.
The raw error as printed by Firefox is included below:
`TypeError: Clipboard is not a constructor`
`var clipboardDemos = new Clipboard('[data-clipboard-demo]'); demos.js (line 1, col 26)`
I have reproduced this on Firefox and Chromium on Windows and Firefox on Linux.

**Comment by ChrRaz** [comment]
Also looking at the commit list this seems to relate to the release of the 1.5.6 release.
An entire release is not much to go from but I suspect it is a place to start. Hope it helps.
I really like the project btw. Great work!

**Comment by myoung8** [comment]
we also had Clipboard break when using it via Ember on v1.5.6 (had to revert to 1.5.5)

Here's the error we got:

```
TypeError: Clipboard is not a function
```

And here's how we import it, FWIW:

```
app.import('bower_components/clipboard/dist/clipboard.js');
```

**Comment by sadiqmmm** [comment]
Getting Error on Clipboard v1.5.6, working fine on v1.5.5.

**In  Chrome Console**
`Uncaught TypeError: Clipboard is not a function`

**In firefox console**
`TypeError: Clipboard is not a constructor  `

**Comment by dduponchel** [comment]
When debugging, I found that `Clipboard` is an object containing the constructor in `default` (I have the same issue on a web application using requirejs). I think it comes from the babel 6 migration in ee1eb45 (see [that stackoverflow question](http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default)).

**Comment by QuentinFchx** [comment]
:-1: Please make sure a patch release does not break the whole thing...

**Comment by zenorocha** [comment]
Take it easy boys, it seems like Babel 6 broke the v1.5.6 release. I'll work on a patch asap.

**Comment by zenorocha** [comment]
Just released 1.5.7. Everything should be working fine now ;)

**Comment by d-theo** [comment]
hi,
I'm having the exact same issue with systemjs-builder, any idea how I could solve the problem ?
